FROM python:3.11-slim

WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy app files
COPY app.py .
COPY model_predict.py .
COPY models ./models

EXPOSE 8501

CMD ["streamlit", "run", "app.py", "--server.address=0.0.0.0"]